### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by brookebachman** [learn-co-curriculum/cli-applications-jukebox#2]
If we're diligent in these steps, the problem usually **popus up** 

Please fix this.

**Comment by maxwellbenton** [comment]
HI @brookebachman00,

Thank you for opening this issue. Unfortunately, I was unable to locate the typo you've listed here in the Readme of this lesson. Is it possible this was meant for a different repository?

I've gone ahead and spell checked this lesson's content, just in case. Since it doesn't look like this typo is present, I am going to close this issue. However, if you feel that this is not resolved and can provide additional information for where the typo is located, please feel free to re-open and I will be happy to take a look.

Thank you!
